/** @type {import('tailwindcss').Config} */
// Sprout & Spark 设计令牌 → Tailwind。源：DESIGN.md（清新绿 + 暖白 + 金点睛，禁暗黑）。
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: '#58CC02',
        'brand-green': '#58CC02',
        'deep-green': '#43C000',
        'soft-green': '#7AC70C',
        'light-green': '#A8E06C',
        mint: '#E8F5E9',
        'mint-deep': '#D3EFD6',
        'warm-white': '#FAFAF5',
        'off-white': '#F5F5F0',
        'light-gray': '#E8E8E3',
        sunshine: '#FFC800',
        'soft-gold': '#FFD54F',
        'light-yellow': '#FFF8E1',
        coral: '#FF8A65',
        'coral-soft': '#FFD4C7',
        sky: '#5BB3F0',
        'sky-soft': '#DCEEFB',
        correct: '#4CAF50',
        warn: '#FF9800',
        'text-primary': '#2D3436',
        'text-secondary': '#636E72',
        'text-hint': '#B2BEC3',
      },
      fontFamily: {
        sans: ['Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        display: ['"Space Grotesk"', 'Inter', 'sans-serif'],
        word: ['"Crimson Pro"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        cjk: ['"Noto Sans SC"', 'sans-serif'],
      },
      fontSize: {
        // 大标题用 clamp 流式字号: 手机自动缩小、桌面回到设计值 (H5 一处改全站响应)
        display: ['clamp(28px, 6.5vw, 44px)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-sm': ['clamp(24px, 5vw, 32px)', { lineHeight: '1.15', fontWeight: '700' }],
        headline: ['clamp(22px, 4.5vw, 28px)', { lineHeight: '1.2', fontWeight: '600' }],
        title: ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'word-hero': ['clamp(34px, 9vw, 56px)', { lineHeight: '1.1', fontWeight: '600' }],
        word: ['clamp(26px, 6vw, 32px)', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6' }],
        'label-caps': ['12px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '600' }],
        phonetic: ['14px', { lineHeight: '1.4' }],
      },
      borderRadius: {
        sm: '0.375rem',
        DEFAULT: '0.625rem',
        md: '0.625rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 2px 12px rgba(88, 204, 2, 0.06), 0 1px 3px rgba(45, 52, 54, 0.04)',
        'card-hover': '0 8px 24px rgba(88, 204, 2, 0.12), 0 2px 6px rgba(45, 52, 54, 0.06)',
        popup: '0 12px 32px rgba(45, 52, 54, 0.12)',
        float: '0 8px 28px rgba(88, 204, 2, 0.22)',
        'btn-3d': '0 3px 0 #43C000',
        'btn-3d-active': '0 1px 0 #43C000',
      },
      spacing: {
        gutter: '24px',
        'page': '32px',
        'page-margin': '32px',
        'card-pad': '24px',
        section: '64px',
      },
      maxWidth: {
        reading: '720px',
        card: '480px',
        content: '1120px',
      },
      keyframes: {
        shimmer: { '100%': { transform: 'translateX(100%)' } },
        'pulse-ring': {
          '0%': { transform: 'scale(0.9)', opacity: '0.6' },
          '70%': { transform: 'scale(1.3)', opacity: '0' },
          '100%': { opacity: '0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'spark-pop': {
          '0%': { transform: 'scale(0) rotate(-20deg)', opacity: '0' },
          '60%': { transform: 'scale(1.15) rotate(8deg)', opacity: '1' },
          '100%': { transform: 'scale(1) rotate(0)', opacity: '1' },
        },
        'dot-bounce': {
          '0%, 80%, 100%': { transform: 'translateY(0)', opacity: '0.4' },
          '40%': { transform: 'translateY(-5px)', opacity: '1' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.6s infinite',
        'pulse-ring': 'pulse-ring 1.8s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        float: 'float 4s ease-in-out infinite',
        'fade-in': 'fade-in 0.3s ease',
        'fade-up': 'fade-up 0.4s cubic-bezier(0.22, 1, 0.36, 1)',
        'spark-pop': 'spark-pop 0.5s cubic-bezier(0.22, 1, 0.36, 1)',
        'dot-bounce': 'dot-bounce 1.4s infinite ease-in-out',
      },
      backdropBlur: {
        glass: '16px',
      },
    },
  },
  plugins: [],
}
